// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOWBpk2JHeobVDFy2twfcXd8wY3USf57U',
    appId: '1:68577278195:web:7ffea5c84c4ed71fc5df86',
    messagingSenderId: '68577278195',
    projectId: 'smart-inventory-779c2',
    authDomain: 'smart-inventory-779c2.firebaseapp.com',
    storageBucket: 'smart-inventory-779c2.firebasestorage.app',
    measurementId: 'G-3SHKSMWNP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABtjdLkdi5jwprgKPsaQ30iyvTFQg4vEk',
    appId: '1:68577278195:android:df52d56102ebf170c5df86',
    messagingSenderId: '68577278195',
    projectId: 'smart-inventory-779c2',
    storageBucket: 'smart-inventory-779c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASWXAwqrbORdPSGxZyGoH0FKIpHNoh090',
    appId: '1:68577278195:ios:58f617e07cbf52efc5df86',
    messagingSenderId: '68577278195',
    projectId: 'smart-inventory-779c2',
    storageBucket: 'smart-inventory-779c2.firebasestorage.app',
    iosBundleId: 'com.example.smartInventory2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASWXAwqrbORdPSGxZyGoH0FKIpHNoh090',
    appId: '1:68577278195:ios:58f617e07cbf52efc5df86',
    messagingSenderId: '68577278195',
    projectId: 'smart-inventory-779c2',
    storageBucket: 'smart-inventory-779c2.firebasestorage.app',
    iosBundleId: 'com.example.smartInventory2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOWBpk2JHeobVDFy2twfcXd8wY3USf57U',
    appId: '1:68577278195:web:df57b1d4eb5436ccc5df86',
    messagingSenderId: '68577278195',
    projectId: 'smart-inventory-779c2',
    authDomain: 'smart-inventory-779c2.firebaseapp.com',
    storageBucket: 'smart-inventory-779c2.firebasestorage.app',
    measurementId: 'G-NQJCQJM24N',
  );
}
